ENTER_LOGIN_PROMPT = "Enter login"
ENTER_PASSWORD_PROMPT = "Enter password"
LOGIN_MUST_BE_TEXT_PROMPT = "Login must be text"
PASSWORD_MUST_BE_TEXT_PROMPT = "Password must be text"
AUTH_FAILURE_PROMPT = "Auth failed. Please try again"
MAIN_PAGE_PROMPT = "Main menu.\nFor search applications enter \"@{nickname} \" in \"send message\""
BUNDLES_LIST_PROMPT = "Choose application for control launch allowance:\n✅ - Launch authorized \n❌ - Launch prohibited"
BUNDLE_INFO  = "Control app: {bundle_name}\nLast launch: {last_access}\nStatus: {bundle_status}"
BUNDLE_EXECUTION_ALLOWED_PROMPT = "✅ Launch authorized"
BUNDLE_EXECUTION_DENIED_PROMPT = "❌ Launch prohibited"
NO_BUNDLES_PROMPT = "There are no management apps yet"
LOGOUT_PROMPT = "Logging out of the account is successful"
BUNDLE_REMOVED_PROMPT = "🗑 Removed"
LOADING_BUNDLE_PROMPT = "Loading application profile"
BUNDLE_NOT_FOUND_PROMPT = "Application not found"
BUNDLES_LIST_BUTTON = "Application list"
LOGOUT_BUTTON = "Logout"

ACCESS_DENIED_PLEASE_RELOGIN_PROMPT_INLINE = "Unauthorized. To authorize, type /start"
ONLY_CHAT_WITH_BOT_SUPPORT = "Supported only in chat with bot"
NOT_FOUND_INLINE = "No matches found for the query `{request}`"
EDIT_INLINE_PROMPT = "Edit {bundle}"
EDIT_TEXT_TRIGGER = "Edit "

BUNDLE_SWITCH_ALLOW_BUTTON = "✅ Allow launch"
BUNDLE_SWITCH_DENY_BUTTON = "❌ Prohibit launch"
BUNDLE_REMOVE_BUTTON = "🗑 Remove"
TO_BUNDLES_LIST = "↩️  Back to application list"

IS_NO_PAGE_ALERT = "There are no more pages"

ACCESS_DENIED_PLEASE_RELOGIN_PROMPT = "You are not authorized"
